version: '3.3'
services:
  web:
    image: docker.io/nakahamalabs465/simpen-backend
    restart: always
    ports:
      - "10001:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge